apiVersion: v1
kind: Service
metadata:
  name: service-flask-backend
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      name: tcp-5000
      protocol: TCP
  selector:
    app: udacity-capstone-flask